//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfHexaEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfHexaEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the end of file. Do you want append one byte ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string AppendByteConfirmationString {
            get {
                return ResourceManager.GetString("AppendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmarks.
        /// </summary>
        public static string BookmarksString {
            get {
                return ResourceManager.GetString("BookmarksString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte action.
        /// </summary>
        public static string ByteActionString {
            get {
                return ResourceManager.GetString("ByteActionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        public static string BytesTagString {
            get {
                return ResourceManager.GetString("BytesTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        public static string ByteString {
            get {
                return ResourceManager.GetString("ByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel long process.
        /// </summary>
        public static string CancelLongProcessString {
            get {
                return ResourceManager.GetString("CancelLongProcessString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to cancel long process..
        /// </summary>
        public static string CancelLongProcessToolTipString {
            get {
                return ResourceManager.GetString("CancelLongProcessToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear bookmark.
        /// </summary>
        public static string ClearBookMarkString {
            get {
                return ResourceManager.GetString("ClearBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string ClearString {
            get {
                return ResourceManager.GetString("ClearString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to go to at position..
        /// </summary>
        public static string ClickToGoAtPositionString {
            get {
                return ResourceManager.GetString("ClickToGoAtPositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseString {
            get {
                return ResourceManager.GetString("CloseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert this string to long.
        /// </summary>
        public static string ConvertStringToLongErrorString {
            get {
                return ResourceManager.GetString("ConvertStringToLongErrorString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as ASCII.
        /// </summary>
        public static string CopyAsASCIIString {
            get {
                return ResourceManager.GetString("CopyAsASCIIString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as decimal.
        /// </summary>
        public static string CopyAsDecimalString {
            get {
                return ResourceManager.GetString("CopyAsDecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy as hexadecimal.
        /// </summary>
        public static string CopyAsHexadecimalString {
            get {
                return ResourceManager.GetString("CopyAsHexadecimalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBL string (character file loaded).
        /// </summary>
        public static string CopyAsTBLString {
            get {
                return ResourceManager.GetString("CopyAsTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selection as ....
        /// </summary>
        public static string CopySelectionAsString {
            get {
                return ResourceManager.GetString("CopySelectionAsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of.
        /// </summary>
        public static string CountOfString {
            get {
                return ResourceManager.GetString("CountOfString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default TBL.
        /// </summary>
        public static string DefaultTBLString {
            get {
                return ResourceManager.GetString("DefaultTBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteString {
            get {
                return ResourceManager.GetString("DeleteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionString {
            get {
                return ResourceManager.GetString("DescriptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00=&lt;NUL&gt;
        ///01=&lt;SOH&gt;
        ///02=&lt;STX&gt;
        ///03=&lt;ETX&gt;
        ///04=&lt;PF&gt;
        ///05=&lt;HT&gt;
        ///06=&lt;LC&gt;
        ///07=&lt;DEL&gt;
        ///08=&lt;GE&gt;
        ///09=&lt;RLF&gt;
        ///0A=&lt;SMM&gt;
        ///0B=&lt;VT&gt;
        ///0C=&lt;FF&gt;
        ///0D=&lt;CR&gt;
        ///0E=&lt;SO&gt;
        ///0F=&lt;SI&gt;
        ///10=&lt;DLE&gt;
        ///11=&lt;DC1&gt;
        ///12=&lt;DC2&gt;
        ///13=&lt;TM&gt;
        ///14=&lt;RES&gt;
        ///15=&lt;NL&gt;
        ///16=&lt;BS&gt;
        ///17=&lt;IL&gt;
        ///18=&lt;CAN&gt;
        ///19=&lt;EM&gt;
        ///1A=&lt;CC&gt;
        ///1B=&lt;CU1&gt;
        ///1C=&lt;IFS&gt;
        ///1D=&lt;IGS&gt;
        ///1E=&lt;IRS&gt;
        ///1F=&lt;IUS&gt;
        ///20=&lt;DS&gt;
        ///21=&lt;SOS&gt;
        ///22=&lt;FS&gt;
        ///23=.
        ///24=&lt;BYP&gt;
        ///25=&lt;LF&gt;
        ///26=&lt;ETB&gt;
        ///27=&lt;ESC&gt;
        ///28=.
        ///29=.
        ///2A=&lt;SM&gt;
        ///2B=&lt;CU2&gt;
        ///2C=.
        ///2D=&lt;ENQ&gt;
        ///2E=&lt;ACK&gt;
        ///2F=&lt;BEL&gt;
        ///30=.
        ///31=.
        ///32=&lt;SYN&gt;
        ///33=.
        ///34=&lt;PN&gt;
        ///35=&lt;RS&gt;
        ///36=&lt;UC&gt;
        ///37=&lt;EOT&gt;
        ///38 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EBCDIC {
            get {
                return ResourceManager.GetString("EBCDIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 00=.
        ///01=.
        ///02=.
        ///03=.
        ///04=.
        ///05=.
        ///06=.
        ///07=.
        ///08=.
        ///09=.
        ///0A=.
        ///0B=.
        ///0C=.
        ///0D=.
        ///0E=.
        ///0F=.
        ///10=.
        ///11=.
        ///12=.
        ///13=.
        ///14=.
        ///15=.
        ///16=.
        ///17=.
        ///18=.
        ///19=.
        ///1A=.
        ///1B=.
        ///1C=.
        ///1D=.
        ///1E=.
        ///1F=.
        ///20=.
        ///21=.
        ///22=.
        ///23=.
        ///24=.
        ///25=.
        ///26=.
        ///27=.
        ///28=.
        ///29=.
        ///2A=.
        ///2B=.
        ///2C=.
        ///2D=.
        ///2E=.
        ///2F=.
        ///30=.
        ///31=.
        ///32=.
        ///33=.
        ///34=.
        ///35=.
        ///36=.
        ///37=.
        ///38=.
        ///39=.
        ///3A=.
        ///3B=.
        ///3C=.
        ///3D=.
        ///3E=.
        ///3F=.
        ///40=.
        ///41=.
        ///42=.
        ///43=.
        ///44=.
        ///45=.
        ///46=.
        ///47=.
        ///48=.
        ///49=.
        ///4A=¢
        ///4B=.
        ///4C=&lt;
        ///4D=(
        ///4E=+
        ///4F=|
        ///50=&amp;
        ///51=.
        ///52=.
        ///53=.
        ///54=.
        ///55 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EBCDICNoSpecialChar {
            get {
                return ResourceManager.GetString("EBCDICNoSpecialChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;end&gt;.
        /// </summary>
        public static string EndTagString {
            get {
                return ResourceManager.GetString("EndTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter hexadecimal value ....
        /// </summary>
        public static string EnterHexValueMsgString {
            get {
                return ResourceManager.GetString("EnterHexValueMsgString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want close the current file and open : .
        /// </summary>
        public static string FileDroppingConfirmationString {
            get {
                return ResourceManager.GetString("FileDroppingConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill selection with byte.
        /// </summary>
        public static string FillSelectionAloneString {
            get {
                return ResourceManager.GetString("FillSelectionAloneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill selection with byte....
        /// </summary>
        public static string FillSelectionString {
            get {
                return ResourceManager.GetString("FillSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find All.
        /// </summary>
        public static string FindAllString {
            get {
                return ResourceManager.GetString("FindAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplaceString {
            get {
                return ResourceManager.GetString("FindAndReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte to search.
        /// </summary>
        public static string FindByteString {
            get {
                return ResourceManager.GetString("FindByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find First.
        /// </summary>
        public static string FindFirstString {
            get {
                return ResourceManager.GetString("FindFirstString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Last.
        /// </summary>
        public static string FindLastString {
            get {
                return ResourceManager.GetString("FindLastString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        public static string FindNextString {
            get {
                return ResourceManager.GetString("FindNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find all occurence of selection.
        /// </summary>
        public static string FindSelectionString {
            get {
                return ResourceManager.GetString("FindSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindString {
            get {
                return ResourceManager.GetString("FindString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find what:.
        /// </summary>
        public static string FindWhatString {
            get {
                return ResourceManager.GetString("FindWhatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First byte.
        /// </summary>
        public static string FirstByteString {
            get {
                return ResourceManager.GetString("FirstByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hex.
        /// </summary>
        public static string HexString {
            get {
                return ResourceManager.GetString("HexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight all data find.
        /// </summary>
        public static string HighLightSettingString {
            get {
                return ResourceManager.GetString("HighLightSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kb.
        /// </summary>
        public static string KBTagString {
            get {
                return ResourceManager.GetString("KBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string LengthString {
            get {
                return ResourceManager.GetString("LengthString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ln.
        /// </summary>
        public static string LineStatusBarTagString {
            get {
                return ResourceManager.GetString("LineStatusBarTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ln&gt;.
        /// </summary>
        public static string LineTagString {
            get {
                return ResourceManager.GetString("LineTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long.
        /// </summary>
        public static string LongString {
            get {
                return ResourceManager.GetString("LongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mb.
        /// </summary>
        public static string MBTagString {
            get {
                return ResourceManager.GetString("MBTagString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkString {
            get {
                return ResourceManager.GetString("OkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is locked. Do you want to open it in read-only mode?.
        /// </summary>
        public static string OpenAsReadOnlyString {
            get {
                return ResourceManager.GetString("OpenAsReadOnlyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste operation reached the end of file. Do you want extend the file for complete operation ? This operation cannot be canceled if you continue..
        /// </summary>
        public static string PasteExtendByteConfirmationString {
            get {
                return ResourceManager.GetString("PasteExtendByteConfirmationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clipboard.
        /// </summary>
        public static string PasteFromClipboardString {
            get {
                return ResourceManager.GetString("PasteFromClipboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste without inserting.
        /// </summary>
        public static string PasteNotInsertString {
            get {
                return ResourceManager.GetString("PasteNotInsertString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionString {
            get {
                return ResourceManager.GetString("PositionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        public static string ReplaceAllString {
            get {
                return ResourceManager.GetString("ReplaceAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace by byte.
        /// </summary>
        public static string ReplaceByByteString {
            get {
                return ResourceManager.GetString("ReplaceByByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Next.
        /// </summary>
        public static string ReplaceNextString {
            get {
                return ResourceManager.GetString("ReplaceNextString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace byte in selection....
        /// </summary>
        public static string ReplaceSelectionString {
            get {
                return ResourceManager.GetString("ReplaceSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string ReplaceString {
            get {
                return ResourceManager.GetString("ReplaceString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trim the data on the find length when replace.
        /// </summary>
        public static string ReplaceTrimSettingString {
            get {
                return ResourceManager.GetString("ReplaceTrimSettingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with byte.
        /// </summary>
        public static string ReplaceWithByteString {
            get {
                return ResourceManager.GetString("ReplaceWithByteString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace with:.
        /// </summary>
        public static string ReplaceWithString {
            get {
                return ResourceManager.GetString("ReplaceWithString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        public static string SelectAllString {
            get {
                return ResourceManager.GetString("SelectAllString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set bookmark.
        /// </summary>
        public static string SetBookMarkString {
            get {
                return ResourceManager.GetString("SetBookMarkString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBL.
        /// </summary>
        public static string TBLString {
            get {
                return ResourceManager.GetString("TBLString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This string are not hex.
        /// </summary>
        public static string ThisStringAreNotHexString {
            get {
                return ResourceManager.GetString("ThisStringAreNotHexString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UndoString {
            get {
                return ResourceManager.GetString("UndoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueString {
            get {
                return ResourceManager.GetString("ValueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error is occurs when writing..
        /// </summary>
        public static string WritingErrorExeptionString {
            get {
                return ResourceManager.GetString("WritingErrorExeptionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset zoom to 100%.
        /// </summary>
        public static string ZoomResetString {
            get {
                return ResourceManager.GetString("ZoomResetString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomString {
            get {
                return ResourceManager.GetString("ZoomString", resourceCulture);
            }
        }
    }
}
